POST http://localhost:3333/tasks
Content-Type: application/json

//body
{
    "name": "xxxx",
    "description": "xxxxxxxxxx"
}

###

GET http://localhost:3333/tasks

###
//Tem q passar o ID
PATCH http://localhost:3333/tasks/
Content-Type: application/json

//body
{
    "newSpot": 3
}


###
//Tem q passar o ID
DELETE http://localhost:3333/tasks/